server:
  port: 8000
  jackson:
    time-zone: Asia/Seoul
  servlet:
    context-path: /spam
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  timezone: Asia/Seoul

spring:
  datasource:
    url: jdbc:mysql://106.243.194.229:3100/spam?serverTimezone=Asia/Seoul
    username: icia97
    password: '1234'
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  web:
    resources: 
      static-locations: classpath:/static/
     
  mail:
    host: smtp.gmail.com
    port: 465
    username: byyb2696@gmail.com
    password: btsqzqxlkcujzxdo
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

mybatis:
  type-aliases-package: com.spam9700.spam.dto
  mapper-locations: classpath:/mappers/*.xml
    
logging:
  level:
    root: info
  
log4jdbc:
  spylogdelegator:
    name: net.sf.log4jdbc.log.slf4j.Slf4jSpyLogDelegator
  dump:
    sql:
      maxlinelength: 0
  resultsettable:
    format: markdown
    margin: 5


# Logback Extensions 기능
# logback-spring.xml 파일에서만 사용가능
# <springProfiles></springProfiles> 태그 활용 가능
# <configuration scan="true" scanPeriod="30 seconds"> 사용 불가
---
appender:
  console:
    name: console
    class: ch.qos.logback.core.ConsoleAppender
    encoder:
      pattern: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

logger:
  com.spam9700.spam:
    level: debug
  jdbc.resultsettable:
    level: trace
  jdbc.resultset:
    level: trace
  jdbc.sqlonly:
    level: trace
  jdbc.audit:
    level: off
  jdbc.sqltiming:
    level: off
  jdbc.connection:
    level: off

root:
  level: off
  appender-ref:
    ref: console

